apiVersion: v1
kind: Service
metadata:
  name: velocity
  namespace: mineshark
  labels:
    app: velocity
spec:
  type: NodePort
  selector:
    app: velocity
  ports:
    - name: minecraft-java
      port: 25577
      targetPort: 25577
      # k3d loadbalancer mappe 25565 (hôte) → 30565 (node) → 25577 (pod)
      nodePort: 30565
      protocol: TCP
    - name: minecraft-bedrock
      port: 19132
      targetPort: 19132
      nodePort: 30132
      protocol: UDP
