apiVersion: v1
kind: Service
metadata:
  name: velocity
  namespace: mineshark
  labels:
    app: velocity
spec:
  type: ClusterIP
  selector:
    app: velocity
  ports:
    - containerPort: 25577
      hostPort: 25565 # Joueurs se connectent sur :25565
      protocol: TCP
    - containerPort: 19132
      hostPort: 19132 # Bedrock direct
      protocol: UDP
