# docker-compose.override.yml (pas commité, uniquement pour test local)
# Réduit la RAM pour tester sur un PC avec moins de ressources
services:
  main-paper:
    environment:
      MEMORY: "512M"
  game-paper:
    environment:
      MEMORY: "1G"
  mod-neoforge:
    environment:
      MEMORY: "4G"
